name: build
on:
  pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: bridgecrew-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Bridgecrew action
        id: bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
          api-key: ${{secrets.bridgecrew_api_key}}
